// config.js (auto-generated by GitHub Actions)
export const config = {
    "Video API" = "https://piped.video/",
    "Sponsorblock" = "https://sponsor.ajay.app/",
    "Dearrow" = "https://github.com/ajayyy/DeArrow"
};
